### ISSUE TITLE
TF4.1 - Protótipo de alta fidelidade

### ISSUE THREAD

**Issue by GeovanaRamos** [ads-unigrade-2019-1/App#1]
## Protótipo de alta fidelidade

Gerar todas as telas do app, além do logotipo vetorizado e a nova paleta de cores.

**Comment by guilherme1guy** [comment]
A issue será trabalhada no repositório: https://github.com/ads-unigrade-2019-1/Prototipo para evitar problemas com o código final do App.

**Comment by GeovanaRamos** [comment]
Protótipo teve uma base feita no repositório e uma parte complementar feita em desenhos e validada com o time.
